#floyd

In [7]:
import numpy as np
n=int(input())
m=int(input())
a=np.zeros((n+1,n+1))
for i in range(n+1):
    for j in range(n+1):
        a[i][j]=100
for i in range(m):
    i,j=input().split()
    i=int(i)
    j=int(j)
    a[i][j]=1
    a[j][i]=1
for k in range(1,n+1):
    for i in range(1,n+1):
        for j in range(1,n+1):
            a[i][j]=min(a[i][k]+a[k][j],a[i][j])

print(a)


[[100. 100. 100. 100. 100. 100. 100.]
 [100.   2.   3.   1.   2.   2.   1.]
 [100.   3.   2.   2.   1.   3.   2.]
 [100.   1.   2.   2.   1.   1.   2.]
 [100.   2.   1.   1.   2.   2.   1.]
 [100.   2.   3.   1.   2.   2.   3.]
 [100.   1.   2.   2.   1.   3.   2.]]
